/**
 * Curio — Today in History.
 *
 * A companion to your own diary: what the world was doing on this date.
 *
 * The dataset is bundled, so it works with the radio off like everything else
 * here. When you happen to be online, Curio can quietly enrich the day from
 * Wikipedia's public "on this day" feed — no key, no account, and it never
 * sends anything about you. That call is optional and fails silently.
 *
 * Entries are [year, what happened, tag].
 */

export const TAGS = ['science', 'politics', 'culture', 'rights', 'exploration', 'tech', 'disaster', 'sport'];

export const HISTORY = {
  '01-01': [[1959, 'Cuban revolutionaries entered Havana as Batista fled the country.', 'politics'],
            [1993, 'Czechoslovakia peacefully split into the Czech Republic and Slovakia.', 'politics'],
            [1999, 'The euro was introduced as an accounting currency across eleven nations.', 'politics']],
  '01-02': [[1959, 'The Soviet probe Luna 1 became the first craft to leave Earth\u2019s gravity.', 'exploration'],
            [1900, 'US Secretary of State John Hay announced the Open Door Policy on China.', 'politics']],
  '01-03': [[1888, 'The first commercially successful drinking straw was patented.', 'tech'],
            [1959, 'Alaska was admitted as the 49th state of the United States.', 'politics']],
  '01-04': [[1643, 'Isaac Newton was born in Woolsthorpe, Lincolnshire.', 'science'],
            [2004, 'NASA\u2019s rover Spirit landed on Mars and began exploring Gusev crater.', 'exploration']],
  '01-05': [[1933, 'Construction began on the Golden Gate Bridge in San Francisco.', 'tech'],
            [1957, 'The Eisenhower Doctrine on the Middle East was announced.', 'politics']],
  '01-06': [[1912, 'Alfred Wegener first presented his theory of continental drift.', 'science'],
            [1929, 'Mother Teresa arrived in Calcutta to begin her work among the poor.', 'culture']],
  '01-07': [[1610, 'Galileo observed the first three moons of Jupiter through his telescope.', 'science'],
            [1927, 'The first transatlantic telephone call was made, London to New York.', 'tech']],
  '01-08': [[1889, 'Herman Hollerith patented the punched-card tabulating machine.', 'tech'],
            [1815, 'The Battle of New Orleans was fought, weeks after the war had formally ended.', 'politics']],
  '01-09': [[2007, 'Apple unveiled the first iPhone at Macworld in San Francisco.', 'tech'],
            [1799, 'Britain introduced income tax to fund the Napoleonic Wars.', 'politics']],
  '01-10': [[1863, 'The world\u2019s first underground railway opened in London.', 'tech'],
            [1946, 'The first General Assembly of the United Nations opened in London.', 'politics']],
  '01-11': [[1922, 'Insulin was first used successfully to treat diabetes in a patient.', 'science'],
            [1935, 'Amelia Earhart flew solo from Hawaii to California.', 'exploration']],
  '01-12': [[2010, 'A catastrophic earthquake struck Haiti near Port-au-Prince.', 'disaster'],
            [1976, 'Agatha Christie, the best-selling novelist of all time, died at 85.', 'culture']],
  '01-13': [[1888, 'The National Geographic Society was founded in Washington, DC.', 'science'],
            [1910, 'The first public radio broadcast, an opera from the Met, went out in New York.', 'tech']],
  '01-14': [[1954, 'Marilyn Monroe married Joe DiMaggio in San Francisco.', 'culture'],
            [2005, 'The Huygens probe landed on Titan, Saturn\u2019s largest moon.', 'exploration']],
  '01-15': [[1929, 'Martin Luther King Jr. was born in Atlanta, Georgia.', 'rights'],
            [2001, 'Wikipedia was launched.', 'tech']],
  '01-16': [[1969, 'Soyuz 4 and Soyuz 5 performed the first docking of two crewed spacecraft.', 'exploration'],
            [1920, 'Prohibition began in the United States.', 'politics']],
  '01-17': [[1994, 'The Northridge earthquake struck Los Angeles.', 'disaster'],
            [1929, 'Popeye the Sailor first appeared in a newspaper comic strip.', 'culture']],
  '01-18': [[1919, 'The Paris Peace Conference opened after the First World War.', 'politics'],
            [1778, 'James Cook became the first European to reach the Hawaiian Islands.', 'exploration']],
  '01-19': [[2006, 'NASA launched New Horizons on its long journey to Pluto.', 'exploration'],
            [1883, 'The first electric lighting system using overhead wires began service.', 'tech']],
  '01-20': [[1961, 'John F. Kennedy was inaugurated as US president.', 'politics'],
            [2009, 'Barack Obama was inaugurated as the first Black US president.', 'rights']],
  '01-21': [[1976, 'Concorde began commercial supersonic passenger service.', 'tech'],
            [1954, 'The first nuclear-powered submarine, USS Nautilus, was launched.', 'tech']],
  '01-22': [[1901, 'Queen Victoria died after a reign of more than 63 years.', 'politics'],
            [1984, 'The Apple Macintosh was introduced with a famous Super Bowl advertisement.', 'tech']],
  '01-23': [[1960, 'The bathyscaphe Trieste reached the deepest point of the Mariana Trench.', 'exploration'],
            [1849, 'Elizabeth Blackwell became the first woman to earn a medical degree in the US.', 'rights']],
  '01-24': [[1848, 'Gold was discovered at Sutter\u2019s Mill, starting the California Gold Rush.', 'exploration'],
            [1908, 'The Boy Scout movement began in England.', 'culture']],
  '01-25': [[1919, 'The League of Nations was founded at the Paris Peace Conference.', 'politics'],
            [1924, 'The first Winter Olympic Games opened in Chamonix, France.', 'sport']],
  '01-26': [[1788, 'The First Fleet arrived at Sydney Cove, beginning European settlement of Australia.', 'exploration'],
            [1926, 'John Logie Baird gave the first public demonstration of television.', 'tech']],
  '01-27': [[1945, 'Auschwitz was liberated by Soviet troops.', 'rights'],
            [1967, 'The Outer Space Treaty was signed, barring weapons of mass destruction in orbit.', 'politics']],
  '01-28': [[1986, 'The Space Shuttle Challenger broke apart shortly after launch.', 'disaster'],
            [1813, 'Jane Austen\u2019s Pride and Prejudice was first published.', 'culture']],
  '01-29': [[1886, 'Karl Benz patented the first practical petrol-powered automobile.', 'tech'],
            [1856, 'Queen Victoria instituted the Victoria Cross.', 'politics']],
  '01-30': [[1948, 'Mohandas Gandhi was assassinated in New Delhi.', 'politics'],
            [1969, 'The Beatles gave their last public performance, on a London rooftop.', 'culture']],
  '01-31': [[1958, 'Explorer 1, the first US satellite, discovered the Van Allen radiation belts.', 'science'],
            [1990, 'The first McDonald\u2019s in the Soviet Union opened in Moscow.', 'culture']],

  '02-01': [[1884, 'The first volume of the Oxford English Dictionary was published.', 'culture'],
            [1960, 'Four students began the Greensboro sit-ins against segregation.', 'rights']],
  '02-02': [[1935, 'The polygraph was used in court evidence for the first time.', 'tech'],
            [1971, 'The Ramsar Convention on wetlands was signed in Iran.', 'science']],
  '02-03': [[1966, 'Luna 9 made the first soft landing on the Moon and sent back pictures.', 'exploration'],
            [1913, 'The 16th Amendment authorised a US federal income tax.', 'politics']],
  '02-04': [[2004, 'Facebook was launched from a Harvard dormitory.', 'tech'],
            [1789, 'George Washington was unanimously elected the first US president.', 'politics']],
  '02-05': [[1971, 'Apollo 14 landed on the Moon in the Fra Mauro highlands.', 'exploration'],
            [1885, 'The Congo Free State was established under Leopold II of Belgium.', 'politics']],
  '02-06': [[1952, 'Elizabeth II acceded to the British throne.', 'politics'],
            [1971, 'Alan Shepard hit two golf balls on the surface of the Moon.', 'sport']],
  '02-07': [[1964, 'The Beatles arrived in New York, beginning the British Invasion.', 'culture'],
            [1992, 'The Maastricht Treaty was signed, creating the European Union.', 'politics']],
  '02-08': [[1587, 'Mary, Queen of Scots was executed at Fotheringhay Castle.', 'politics'],
            [1915, 'The film Birth of a Nation premiered, prompting immediate protest.', 'culture']],
  '02-09': [[1964, 'The Beatles appeared on the Ed Sullivan Show before 73 million viewers.', 'culture'],
            [1943, 'The Battle of Guadalcanal ended in Allied victory.', 'politics']],
  '02-10': [[1996, 'Deep Blue beat world champion Garry Kasparov in a game of chess.', 'tech'],
            [1840, 'Queen Victoria married Prince Albert.', 'culture']],
  '02-11': [[1990, 'Nelson Mandela was released after 27 years in prison.', 'rights'],
            [1847, 'Thomas Edison was born in Milan, Ohio.', 'tech']],
  '02-12': [[1809, 'Charles Darwin and Abraham Lincoln were both born, on the same day.', 'science'],
            [1999, 'The impeachment trial of Bill Clinton ended in acquittal.', 'politics']],
  '02-13': [[1633, 'Galileo arrived in Rome to face the Inquisition.', 'science'],
            [1960, 'France tested its first atomic bomb in the Algerian Sahara.', 'politics']],
  '02-14': [[1876, 'Alexander Graham Bell filed his patent for the telephone.', 'tech'],
            [1990, 'Voyager 1 turned around and photographed the \u201cPale Blue Dot\u201d.', 'exploration']],
  '02-15': [[1965, 'Canada adopted the maple leaf flag.', 'culture'],
            [1946, 'ENIAC, one of the first general-purpose computers, was unveiled.', 'tech']],
  '02-16': [[1923, 'Howard Carter opened the burial chamber of Tutankhamun.', 'culture'],
            [2005, 'The Kyoto Protocol on greenhouse gases came into force.', 'science']],
  '02-17': [[1600, 'Giordano Bruno was burned at the stake in Rome for heresy.', 'science'],
            [1904, 'Puccini\u2019s Madama Butterfly premiered at La Scala.', 'culture']],
  '02-18': [[1930, 'Clyde Tombaugh discovered Pluto at the Lowell Observatory.', 'science'],
            [1885, 'Mark Twain published Adventures of Huckleberry Finn in the US.', 'culture']],
  '02-19': [[1878, 'Thomas Edison patented the phonograph.', 'tech'],
            [1945, 'US forces landed on Iwo Jima.', 'politics']],
  '02-20': [[1962, 'John Glenn became the first American to orbit the Earth.', 'exploration'],
            [1986, 'The Soviet Union launched the core module of the Mir space station.', 'exploration']],
  '02-21': [[1848, 'Marx and Engels published The Communist Manifesto.', 'politics'],
            [1965, 'Malcolm X was assassinated in New York City.', 'rights']],
  '02-22': [[1997, 'Scientists announced the birth of Dolly the sheep, the first cloned mammal.', 'science'],
            [1980, 'The US ice hockey team beat the Soviet Union in the \u201cMiracle on Ice\u201d.', 'sport']],
  '02-23': [[1455, 'The Gutenberg Bible, the first major printed book, is traditionally dated.', 'tech'],
            [1997, 'A fire aboard the Mir space station threatened the crew.', 'exploration']],
  '02-24': [[1582, 'Pope Gregory XIII announced the Gregorian calendar.', 'science'],
            [1938, 'The first nylon bristle toothbrush went on sale.', 'tech']],
  '02-25': [[1986, 'The People Power Revolution ended Marcos\u2019s rule in the Philippines.', 'rights'],
            [1836, 'Samuel Colt patented the revolver.', 'tech']],
  '02-26': [[1935, 'Robert Watson-Watt demonstrated radar for the first time.', 'tech'],
            [1993, 'A bomb exploded beneath the World Trade Center in New York.', 'disaster']],
  '02-27': [[1900, 'The British Labour Party was founded.', 'politics'],
            [1964, 'Italy asked for help to keep the Leaning Tower of Pisa from falling.', 'culture']],
  '02-28': [[1953, 'Watson and Crick announced they had found the structure of DNA.', 'science'],
            [1986, 'Swedish prime minister Olof Palme was assassinated in Stockholm.', 'politics']],
  '02-29': [[1504, 'Columbus used a predicted lunar eclipse to overawe Jamaican islanders.', 'exploration'],
            [1940, 'Hattie McDaniel became the first Black performer to win an Academy Award.', 'rights']],

  '03-01': [[1896, 'Henri Becquerel discovered radioactivity.', 'science'],
            [1872, 'Yellowstone became the world\u2019s first national park.', 'science']],
  '03-02': [[1969, 'Concorde made its first test flight, from Toulouse.', 'tech'],
            [1962, 'Wilt Chamberlain scored 100 points in a single basketball game.', 'sport']],
  '03-03': [[1931, 'The Star-Spangled Banner became the US national anthem.', 'culture'],
            [1875, 'Bizet\u2019s Carmen premiered in Paris.', 'culture']],
  '03-04': [[1789, 'The first US Congress met and the Constitution came into force.', 'politics'],
            [1933, 'Frances Perkins became the first woman in a US cabinet.', 'rights']],
  '03-05': [[1946, 'Winston Churchill delivered his \u201cIron Curtain\u201d speech in Missouri.', 'politics'],
            [1953, 'Joseph Stalin died in Moscow.', 'politics']],
  '03-06': [[1869, 'Dmitri Mendeleev presented the first periodic table of elements.', 'science'],
            [1957, 'Ghana became the first sub-Saharan African colony to gain independence.', 'rights']],
  '03-07': [[1876, 'Alexander Graham Bell was granted the telephone patent.', 'tech'],
            [1965, 'Civil rights marchers were attacked on the Edmund Pettus Bridge in Selma.', 'rights']],
  '03-08': [[1911, 'International Women\u2019s Day was marked for the first time.', 'rights'],
            [1817, 'The New York Stock Exchange was formally founded.', 'politics']],
  '03-09': [[1959, 'The Barbie doll went on sale for the first time.', 'culture'],
            [1961, 'Sputnik 9 carried a dog and a mannequin, rehearsing for human spaceflight.', 'exploration']],
  '03-10': [[1876, 'Bell made the first telephone call: \u201cMr Watson, come here.\u201d', 'tech'],
            [1977, 'Astronomers discovered the rings of Uranus.', 'science']],
  '03-11': [[2011, 'A magnitude 9.0 earthquake and tsunami struck Japan.', 'disaster'],
            [1985, 'Mikhail Gorbachev became leader of the Soviet Union.', 'politics']],
  '03-12': [[1930, 'Gandhi began the Salt March in protest against British rule.', 'rights'],
            [1989, 'Tim Berners-Lee circulated his proposal for the World Wide Web.', 'tech']],
  '03-13': [[1781, 'William Herschel discovered the planet Uranus.', 'science'],
            [1930, 'The discovery of Pluto was announced to the public.', 'science']],
  '03-14': [[1879, 'Albert Einstein was born in Ulm, Germany.', 'science'],
            [1994, 'Linux kernel version 1.0.0 was released.', 'tech']],
  '03-15': [[44, 'Julius Caesar was assassinated in the Roman Senate.', 'politics'],
            [1985, 'The first internet domain name, symbolics.com, was registered.', 'tech']],
  '03-16': [[1926, 'Robert Goddard launched the first liquid-fuelled rocket.', 'tech'],
            [1521, 'Ferdinand Magellan\u2019s expedition reached the Philippines.', 'exploration']],
  '03-17': [[1861, 'The Kingdom of Italy was proclaimed.', 'politics'],
            [1958, 'Vanguard 1, still the oldest satellite in orbit, was launched.', 'exploration']],
  '03-18': [[1965, 'Alexei Leonov made the first spacewalk.', 'exploration'],
            [1990, 'Thieves stole thirteen works from the Gardner Museum in Boston.', 'culture']],
  '03-19': [[1932, 'The Sydney Harbour Bridge opened.', 'tech'],
            [1918, 'The US Congress established time zones and daylight saving time.', 'politics']],
  '03-20': [[1852, 'Uncle Tom\u2019s Cabin was published.', 'culture'],
            [1916, 'Einstein published his general theory of relativity.', 'science']],
  '03-21': [[1960, 'The Sharpeville massacre took place in South Africa.', 'rights'],
            [2006, 'The first message was posted on Twitter.', 'tech']],
  '03-22': [[1895, 'The Lumi\u00e8re brothers gave the first private film screening in Paris.', 'culture'],
            [1993, 'Intel shipped the first Pentium processors.', 'tech']],
  '03-23': [[1839, 'The expression \u201cOK\u201d appeared in print for the first time, in Boston.', 'culture'],
            [2001, 'The Mir space station was deliberately de-orbited into the Pacific.', 'exploration']],
  '03-24': [[1989, 'The Exxon Valdez ran aground, spilling oil into Prince William Sound.', 'disaster'],
            [1882, 'Robert Koch announced his discovery of the tuberculosis bacterium.', 'science']],
  '03-25': [[1807, 'The British Parliament abolished the Atlantic slave trade.', 'rights'],
            [1957, 'The Treaty of Rome established the European Economic Community.', 'politics']],
  '03-26': [[1953, 'Jonas Salk announced a successful polio vaccine.', 'science'],
            [1971, 'Bangladesh declared independence from Pakistan.', 'politics']],
  '03-27': [[1977, 'Two jumbo jets collided at Tenerife in the deadliest aviation accident.', 'disaster'],
            [1964, 'The Great Alaska earthquake, the strongest recorded in North America, struck.', 'disaster']],
  '03-28': [[1979, 'A partial meltdown occurred at Three Mile Island in Pennsylvania.', 'disaster'],
            [1930, 'Constantinople and Angora were officially renamed Istanbul and Ankara.', 'politics']],
  '03-29': [[1974, 'Farmers in China uncovered the Terracotta Army near Xi\u2019an.', 'culture'],
            [1867, 'The British North America Act created the Dominion of Canada.', 'politics']],
  '03-30': [[1858, 'Hymen Lipman patented the pencil with an attached eraser.', 'tech'],
            [1867, 'The United States agreed to purchase Alaska from Russia.', 'politics']],
  '03-31': [[1889, 'The Eiffel Tower was inaugurated in Paris.', 'tech'],
            [1959, 'The Dalai Lama began his exile in India.', 'politics']],

  '04-01': [[1976, 'Apple Computer was founded by Jobs, Wozniak and Wayne.', 'tech'],
            [1867, 'Singapore became a British crown colony.', 'politics']],
  '04-02': [[1902, 'The first permanent cinema in the United States opened in Los Angeles.', 'culture'],
            [1982, 'Argentina invaded the Falkland Islands.', 'politics']],
  '04-03': [[1973, 'The first handheld mobile phone call was made in New York.', 'tech'],
            [1948, 'President Truman signed the Marshall Plan into law.', 'politics']],
  '04-04': [[1968, 'Martin Luther King Jr. was assassinated in Memphis.', 'rights'],
            [1949, 'NATO was founded in Washington, DC.', 'politics']],
  '04-05': [[1614, 'Pocahontas married John Rolfe in Virginia.', 'culture'],
            [1994, 'Kurt Cobain died, aged 27.', 'culture']],
  '04-06': [[1896, 'The first modern Olympic Games opened in Athens.', 'sport'],
            [1909, 'Robert Peary claimed to have reached the North Pole.', 'exploration']],
  '04-07': [[1994, 'The Rwandan genocide began.', 'rights'],
            [1948, 'The World Health Organization was established.', 'science']],
  '04-08': [[1904, 'Britain and France signed the Entente Cordiale.', 'politics'],
            [1973, 'Pablo Picasso died in France, aged 91.', 'culture']],
  '04-09': [[1865, 'Robert E. Lee surrendered at Appomattox, effectively ending the US Civil War.', 'politics'],
            [1959, 'NASA introduced the Mercury Seven, America\u2019s first astronauts.', 'exploration']],
  '04-10': [[1912, 'The Titanic left Southampton on her maiden voyage.', 'exploration'],
            [1998, 'The Good Friday Agreement was signed in Northern Ireland.', 'politics']],
  '04-11': [[1970, 'Apollo 13 launched, two days before its oxygen tank ruptured.', 'exploration'],
            [1961, 'The trial of Adolf Eichmann began in Jerusalem.', 'rights']],
  '04-12': [[1961, 'Yuri Gagarin became the first human in space.', 'exploration'],
            [1981, 'The first Space Shuttle, Columbia, was launched.', 'exploration']],
  '04-13': [[1970, 'An explosion crippled Apollo 13 on its way to the Moon.', 'exploration'],
            [1953, 'Ian Fleming published Casino Royale, introducing James Bond.', 'culture']],
  '04-14': [[1912, 'The Titanic struck an iceberg late in the evening.', 'disaster'],
            [2003, 'The Human Genome Project was declared complete.', 'science']],
  '04-15': [[1912, 'The Titanic sank in the North Atlantic.', 'disaster'],
            [1947, 'Jackie Robinson broke baseball\u2019s colour barrier.', 'rights']],
  '04-16': [[1889, 'Charlie Chaplin was born in London.', 'culture'],
            [1963, 'Martin Luther King Jr. wrote his Letter from Birmingham Jail.', 'rights']],
  '04-17': [[1961, 'The Bay of Pigs invasion of Cuba began.', 'politics'],
            [1970, 'Apollo 13 returned safely to Earth.', 'exploration']],
  '04-18': [[1906, 'The San Francisco earthquake and fire destroyed much of the city.', 'disaster'],
            [1955, 'Albert Einstein died in Princeton, New Jersey.', 'science']],
  '04-19': [[1943, 'The Warsaw Ghetto Uprising began.', 'rights'],
            [1770, 'James Cook first sighted the east coast of Australia.', 'exploration']],
  '04-20': [[2010, 'The Deepwater Horizon rig exploded in the Gulf of Mexico.', 'disaster'],
            [1902, 'Marie and Pierre Curie isolated radium chloride.', 'science']],
  '04-21': [[753, 'Rome was traditionally founded, according to legend.', 'culture'],
            [1918, 'The German pilot known as the Red Baron was shot down in France.', 'politics']],
  '04-22': [[1970, 'The first Earth Day was observed.', 'science'],
            [1500, 'Pedro \u00c1lvares Cabral reached the coast of Brazil.', 'exploration']],
  '04-23': [[1616, 'Shakespeare and Cervantes both died, within days of each other.', 'culture'],
            [1985, 'Coca-Cola announced New Coke, withdrawn within months.', 'culture']],
  '04-24': [[1990, 'The Hubble Space Telescope was launched aboard Discovery.', 'exploration'],
            [1916, 'The Easter Rising began in Dublin.', 'politics']],
  '04-25': [[1953, 'Watson and Crick published their DNA paper in Nature.', 'science'],
            [1974, 'The Carnation Revolution restored democracy to Portugal.', 'rights']],
  '04-26': [[1986, 'The Chernobyl nuclear disaster began in Ukraine.', 'disaster'],
            [1937, 'Guernica was bombed, inspiring Picasso\u2019s painting.', 'culture']],
  '04-27': [[1994, 'South Africa held its first fully democratic election.', 'rights'],
            [1521, 'Ferdinand Magellan was killed in the Philippines.', 'exploration']],
  '04-28': [[1947, 'Thor Heyerdahl set sail from Peru on the raft Kon-Tiki.', 'exploration'],
            [1789, 'The mutiny on the Bounty took place in the South Pacific.', 'exploration']],
  '04-29': [[1913, 'Gideon Sundback patented the modern zipper.', 'tech'],
            [1945, 'Dachau concentration camp was liberated.', 'rights']],
  '04-30': [[1993, 'CERN put the World Wide Web into the public domain.', 'tech'],
            [1975, 'The Vietnam War ended with the fall of Saigon.', 'politics']],

  '05-01': [[1886, 'The Chicago strike for the eight-hour day began, later marked as May Day.', 'rights'],
            [1931, 'The Empire State Building opened in New York.', 'tech']],
  '05-02': [[1519, 'Leonardo da Vinci died in France.', 'culture'],
            [1670, 'The Hudson\u2019s Bay Company was chartered.', 'politics']],
  '05-03': [[1791, 'Poland adopted Europe\u2019s first modern written constitution.', 'politics'],
            [1952, 'The first jet airliner service began, London to Johannesburg.', 'tech']],
  '05-04': [[1904, 'The United States began work on the Panama Canal.', 'tech'],
            [1979, 'Margaret Thatcher became Britain\u2019s first woman prime minister.', 'rights']],
  '05-05': [[1961, 'Alan Shepard became the first American in space.', 'exploration'],
            [1818, 'Karl Marx was born in Trier.', 'politics']],
  '05-06': [[1937, 'The airship Hindenburg caught fire at Lakehurst, New Jersey.', 'disaster'],
            [1954, 'Roger Bannister ran the first sub-four-minute mile.', 'sport']],
  '05-07': [[1945, 'Germany signed its unconditional surrender at Reims.', 'politics'],
            [1824, 'Beethoven\u2019s Ninth Symphony premiered in Vienna.', 'culture']],
  '05-08': [[1945, 'Victory in Europe was celebrated across the Allied nations.', 'politics'],
            [1980, 'The World Health Organization declared smallpox eradicated.', 'science']],
  '05-09': [[1960, 'The US approved the first oral contraceptive pill.', 'rights'],
            [1950, 'Robert Schuman proposed the plan that led to the European Union.', 'politics']],
  '05-10': [[1994, 'Nelson Mandela was inaugurated as president of South Africa.', 'rights'],
            [1869, 'The US transcontinental railroad was completed at Promontory Summit.', 'tech']],
  '05-11': [[1997, 'Deep Blue defeated Garry Kasparov in a full chess match.', 'tech'],
            [1857, 'The Indian Rebellion against British rule spread to Delhi.', 'politics']],
  '05-12': [[1820, 'Florence Nightingale was born in Florence.', 'science'],
            [1949, 'The Soviet Union lifted the Berlin blockade.', 'politics']],
  '05-13': [[1981, 'Pope John Paul II was shot in St Peter\u2019s Square.', 'politics'],
            [1888, 'Brazil abolished slavery with the Golden Law.', 'rights']],
  '05-14': [[1796, 'Edward Jenner administered the first smallpox vaccination.', 'science'],
            [1948, 'The State of Israel declared independence.', 'politics']],
  '05-15': [[1928, 'Mickey Mouse first appeared, in the short film Plane Crazy.', 'culture'],
            [1940, 'The first McDonald\u2019s restaurant opened in San Bernardino.', 'culture']],
  '05-16': [[1929, 'The first Academy Awards were presented in Hollywood.', 'culture'],
            [1960, 'Theodore Maiman operated the first working laser.', 'science']],
  '05-17': [[1954, 'Brown v. Board of Education struck down school segregation in the US.', 'rights'],
            [1792, 'The New York Stock Exchange was founded under a buttonwood tree.', 'politics']],
  '05-18': [[1980, 'Mount St Helens erupted in Washington State.', 'disaster'],
            [1804, 'Napoleon Bonaparte was proclaimed Emperor of the French.', 'politics']],
  '05-19': [[1962, 'Marilyn Monroe sang Happy Birthday to President Kennedy.', 'culture'],
            [1536, 'Anne Boleyn was executed at the Tower of London.', 'politics']],
  '05-20': [[1927, 'Charles Lindbergh took off on the first solo transatlantic flight.', 'exploration'],
            [1873, 'Levi Strauss and Jacob Davis patented riveted denim trousers.', 'culture']],
  '05-21': [[1927, 'Lindbergh landed in Paris after 33 hours in the air.', 'exploration'],
            [1932, 'Amelia Earhart completed the first solo transatlantic flight by a woman.', 'exploration']],
  '05-22': [[1960, 'The strongest earthquake ever recorded struck Chile.', 'disaster'],
            [1859, 'Arthur Conan Doyle, creator of Sherlock Holmes, was born.', 'culture']],
  '05-23': [[1949, 'The Federal Republic of Germany was founded.', 'politics'],
            [1934, 'Bonnie and Clyde were killed in Louisiana.', 'culture']],
  '05-24': [[1844, 'Samuel Morse sent the first telegraph message between cities.', 'tech'],
            [1883, 'The Brooklyn Bridge opened to traffic.', 'tech']],
  '05-25': [[1961, 'Kennedy told Congress the US would land a man on the Moon.', 'exploration'],
            [1977, 'Star Wars opened in cinemas.', 'culture']],
  '05-26': [[1897, 'Bram Stoker\u2019s Dracula was published.', 'culture'],
            [1940, 'The evacuation of Dunkirk began.', 'politics']],
  '05-27': [[1937, 'The Golden Gate Bridge opened to pedestrians.', 'tech'],
            [1703, 'Saint Petersburg was founded by Peter the Great.', 'politics']],
  '05-28': [[1987, 'A teenager landed a small plane in Red Square, embarrassing Soviet defences.', 'politics'],
            [1934, 'The Dionne quintuplets were born in Ontario.', 'science']],
  '05-29': [[1953, 'Hillary and Tenzing reached the summit of Everest.', 'exploration'],
            [1919, 'An eclipse expedition confirmed Einstein\u2019s general relativity.', 'science']],
  '05-30': [[1431, 'Joan of Arc was burned at the stake in Rouen.', 'politics'],
            [1911, 'The first Indianapolis 500 was run.', 'sport']],
  '05-31': [[1889, 'The Johnstown Flood killed more than 2,000 people in Pennsylvania.', 'disaster'],
            [1859, 'The clock tower bell later known as Big Ben began keeping time.', 'culture']],

  '06-01': [[1980, 'CNN launched as the first 24-hour news channel.', 'culture'],
            [1495, 'The first written record of Scotch whisky appeared.', 'culture']],
  '06-02': [[1953, 'Elizabeth II was crowned at Westminster Abbey.', 'politics'],
            [1966, 'Surveyor 1 made the first US soft landing on the Moon.', 'exploration']],
  '06-03': [[1965, 'Ed White made the first American spacewalk.', 'exploration'],
            [1937, 'The Duke of Windsor married Wallis Simpson.', 'culture']],
  '06-04': [[1989, 'The Tiananmen Square protests were suppressed in Beijing.', 'rights'],
            [1783, 'The Montgolfier brothers publicly demonstrated their hot-air balloon.', 'tech']],
  '06-05': [[1968, 'Robert F. Kennedy was shot in Los Angeles.', 'politics'],
            [1947, 'George Marshall outlined the plan to rebuild post-war Europe.', 'politics']],
  '06-06': [[1944, 'Allied forces landed in Normandy on D-Day.', 'politics'],
            [1984, 'Tetris was released by Alexey Pajitnov in Moscow.', 'tech']],
  '06-07': [[1948, 'The first stored-program computer ran its first program in Manchester.', 'tech'],
            [1975, 'Sony introduced the Betamax videocassette recorder.', 'tech']],
  '06-08': [[1949, 'George Orwell\u2019s Nineteen Eighty-Four was published.', 'culture'],
            [1969, 'The Beatles\u2019 Abbey Road cover photograph was still two months away.', 'culture']],
  '06-09': [[1934, 'Donald Duck made his first screen appearance.', 'culture'],
            [1954, 'Joseph Welch confronted Senator McCarthy: \u201cHave you no sense of decency?\u201d', 'rights']],
  '06-10': [[1935, 'Alcoholics Anonymous was founded in Akron, Ohio.', 'culture'],
            [1752, 'Benjamin Franklin is said to have flown his kite in a thunderstorm.', 'science']],
  '06-11': [[1963, 'George Wallace stood in the schoolhouse door to block integration.', 'rights'],
            [1509, 'Henry VIII married Catherine of Aragon.', 'politics']],
  '06-12': [[1987, 'Reagan spoke at the Brandenburg Gate: \u201cTear down this wall.\u201d', 'politics'],
            [1942, 'Anne Frank received the diary she would keep in hiding.', 'culture']],
  '06-13': [[1983, 'Pioneer 10 became the first craft to leave the planetary solar system.', 'exploration'],
            [1966, 'The Miranda ruling established the right to be told your rights.', 'rights']],
  '06-14': [[1777, 'The Stars and Stripes was adopted as the flag of the United States.', 'politics'],
            [1919, 'Alcock and Brown began the first non-stop transatlantic flight.', 'exploration']],
  '06-15': [[1215, 'King John sealed Magna Carta at Runnymede.', 'rights'],
            [1896, 'A tsunami struck the S\u0101nriku coast of Japan.', 'disaster']],
  '06-16': [[1963, 'Valentina Tereshkova became the first woman in space.', 'exploration'],
            [1884, 'The first purpose-built roller coaster opened at Coney Island.', 'culture']],
  '06-17': [[1885, 'The Statue of Liberty arrived in New York Harbor.', 'culture'],
            [1972, 'The Watergate break-in took place in Washington, DC.', 'politics']],
  '06-18': [[1815, 'Napoleon was defeated at Waterloo.', 'politics'],
            [1983, 'Sally Ride became the first American woman in space.', 'exploration']],
  '06-19': [[1865, 'Enslaved people in Texas learned of their freedom, now marked as Juneteenth.', 'rights'],
            [1978, 'The Garfield comic strip debuted.', 'culture']],
  '06-20': [[1969, 'The Apollo 11 crew were three days from the Moon.', 'exploration'],
            [1782, 'The Great Seal of the United States was approved.', 'politics']],
  '06-21': [[1948, 'Columbia Records introduced the long-playing record.', 'tech'],
            [2004, 'SpaceShipOne made the first privately funded human spaceflight.', 'exploration']],
  '06-22': [[1633, 'Galileo was forced to recant his support for a Sun-centred solar system.', 'science'],
            [1941, 'Germany invaded the Soviet Union.', 'politics']],
  '06-23': [[1912, 'Alan Turing was born in London.', 'tech'],
            [2016, 'The United Kingdom voted to leave the European Union.', 'politics']],
  '06-24': [[1947, 'Kenneth Arnold\u2019s sighting introduced the phrase \u201cflying saucer\u201d.', 'culture'],
            [1509, 'Henry VIII was crowned King of England.', 'politics']],
  '06-25': [[1950, 'The Korean War began.', 'politics'],
            [1876, 'The Battle of the Little Bighorn was fought in Montana.', 'politics']],
  '06-26': [[1945, 'The United Nations Charter was signed in San Francisco.', 'politics'],
            [2000, 'Rival teams announced the first draft of the human genome.', 'science']],
  '06-27': [[1967, 'The world\u2019s first cash machine opened in Enfield, London.', 'tech'],
            [1954, 'The world\u2019s first nuclear power station began supplying a grid, at Obninsk.', 'tech']],
  '06-28': [[1914, 'Archduke Franz Ferdinand was assassinated in Sarajevo.', 'politics'],
            [1969, 'The Stonewall uprising began in New York.', 'rights']],
  '06-29': [[2007, 'The first iPhone went on sale.', 'tech'],
            [1613, 'The Globe Theatre burned down during a performance.', 'culture']],
  '06-30': [[1908, 'The Tunguska event flattened forest across Siberia.', 'disaster'],
            [1936, 'Gone with the Wind was published.', 'culture']],
  '07-01': [[1867, 'Canada became a self-governing dominion.', 'politics'],
            [1979, 'Sony released the first Walkman.', 'tech']],
  '07-02': [[1937, 'Amelia Earhart disappeared over the Pacific.', 'exploration'],
            [1964, 'The US Civil Rights Act was signed into law.', 'rights']],
  '07-03': [[1886, 'Karl Benz gave the first public outing of his motor car.', 'tech'],
            [1962, 'Algeria gained independence from France.', 'politics']],
  '07-04': [[1776, 'The US Declaration of Independence was adopted.', 'politics'],
            [1997, 'Mars Pathfinder landed and released the Sojourner rover.', 'exploration']],
  '07-05': [[1948, 'Britain\u2019s National Health Service began operating.', 'rights'],
            [1996, 'Dolly the sheep was born in Scotland.', 'science']],
  '07-06': [[1885, 'Louis Pasteur first successfully tested his rabies vaccine.', 'science'],
            [1957, 'John Lennon and Paul McCartney met for the first time.', 'culture']],
  '07-07': [[1928, 'Sliced bread went on sale for the first time, in Missouri.', 'culture'],
            [2005, 'Coordinated bombings struck London\u2019s transport network.', 'disaster']],
  '07-08': [[1889, 'The first issue of the Wall Street Journal was published.', 'politics'],
            [2011, 'The final Space Shuttle mission launched.', 'exploration']],
  '07-09': [[1877, 'The first Wimbledon tennis championship began.', 'sport'],
            [1962, 'Andy Warhol\u2019s soup cans were first exhibited in Los Angeles.', 'culture']],
  '07-10': [[1856, 'Nikola Tesla was born in modern-day Croatia.', 'tech'],
            [1962, 'Telstar relayed the first live transatlantic television pictures.', 'tech']],
  '07-11': [[1979, 'Skylab re-entered the atmosphere over Australia.', 'exploration'],
            [1960, 'To Kill a Mockingbird was published.', 'culture']],
  '07-12': [[1962, 'The Rolling Stones played their first concert, in London.', 'culture'],
            [1543, 'Henry VIII married his sixth wife, Catherine Parr.', 'politics']],
  '07-13': [[1985, 'Live Aid raised money for famine relief on two continents.', 'culture'],
            [1930, 'The first football World Cup began in Uruguay.', 'sport']],
  '07-14': [[1789, 'The storming of the Bastille began the French Revolution.', 'politics'],
            [2015, 'New Horizons made its close flyby of Pluto.', 'exploration']],
  '07-15': [[1799, 'The Rosetta Stone was found in Egypt.', 'culture'],
            [2006, 'Twitter opened to the public.', 'tech']],
  '07-16': [[1969, 'Apollo 11 launched from Cape Kennedy.', 'exploration'],
            [1945, 'The first nuclear device was detonated in the New Mexico desert.', 'science']],
  '07-17': [[1955, 'Disneyland opened in California.', 'culture'],
            [1998, 'The Rome Statute created the International Criminal Court.', 'rights']],
  '07-18': [[1918, 'Nelson Mandela was born in the Eastern Cape.', 'rights'],
            [64, 'The Great Fire of Rome began.', 'disaster']],
  '07-19': [[1848, 'The Seneca Falls Convention on women\u2019s rights opened in New York.', 'rights'],
            [1799, 'Napoleon\u2019s troops uncovered the Rosetta Stone.', 'culture']],
  '07-20': [[1969, 'Apollo 11 landed and Armstrong walked on the Moon.', 'exploration'],
            [1976, 'Viking 1 made the first successful landing on Mars.', 'exploration']],
  '07-21': [[1969, 'Armstrong and Aldrin spent their only hours on the lunar surface.', 'exploration'],
            [1861, 'The First Battle of Bull Run was fought in Virginia.', 'politics']],
  '07-22': [[1933, 'Wiley Post completed the first solo flight around the world.', 'exploration'],
            [1298, 'The Battle of Falkirk was fought in Scotland.', 'politics']],
  '07-23': [[1904, 'The ice cream cone is said to have been popularised at the St Louis World\u2019s Fair.', 'culture'],
            [1962, 'Telstar carried the first public transatlantic satellite broadcast.', 'tech']],
  '07-24': [[1911, 'Hiram Bingham brought Machu Picchu to international attention.', 'exploration'],
            [1969, 'Apollo 11 splashed down safely in the Pacific.', 'exploration']],
  '07-25': [[1978, 'Louise Brown, the first baby conceived by IVF, was born.', 'science'],
            [1909, 'Louis Bl\u00e9riot made the first flight across the English Channel.', 'exploration']],
  '07-26': [[1945, 'Clement Attlee\u2019s Labour Party won a landslide British election.', 'politics'],
            [1956, 'Egypt nationalised the Suez Canal.', 'politics']],
  '07-27': [[1953, 'The Korean War armistice was signed.', 'politics'],
            [1940, 'Bugs Bunny made his official debut.', 'culture']],
  '07-28': [[1914, 'Austria-Hungary declared war on Serbia, beginning the First World War.', 'politics'],
            [1868, 'The Fourteenth Amendment was ratified in the United States.', 'rights']],
  '07-29': [[1958, 'NASA was created by act of Congress.', 'exploration'],
            [1981, 'Charles and Diana married at St Paul\u2019s Cathedral.', 'culture']],
  '07-30': [[1966, 'England won the football World Cup at Wembley.', 'sport'],
            [1971, 'Apollo 15 astronauts drove the first lunar rover.', 'exploration']],
  '07-31': [[1790, 'The first US patent was issued, for a potash process.', 'tech'],
            [1965, 'J. K. Rowling was born in Gloucestershire.', 'culture']],

  '08-01': [[1774, 'Joseph Priestley isolated the gas later named oxygen.', 'science'],
            [1981, 'MTV began broadcasting.', 'culture']],
  '08-02': [[1990, 'Iraq invaded Kuwait.', 'politics'],
            [1858, 'The first Indian Councils Act transferred rule from the East India Company.', 'politics']],
  '08-03': [[1492, 'Christopher Columbus set sail from Palos de la Frontera.', 'exploration'],
            [1958, 'The submarine Nautilus passed beneath the North Pole.', 'exploration']],
  '08-04': [[1914, 'Britain declared war on Germany.', 'politics'],
            [1944, 'Anne Frank and her family were arrested in Amsterdam.', 'rights']],
  '08-05': [[1962, 'Nelson Mandela was arrested near Howick, South Africa.', 'rights'],
            [1963, 'The Partial Nuclear Test Ban Treaty was signed in Moscow.', 'politics']],
  '08-06': [[1945, 'An atomic bomb was dropped on Hiroshima.', 'disaster'],
            [1991, 'Tim Berners-Lee posted the first public description of the World Wide Web.', 'tech']],
  '08-07': [[1947, 'The Kon-Tiki raft reached Polynesia after 101 days at sea.', 'exploration'],
            [1974, 'Philippe Petit walked a wire between the Twin Towers.', 'culture']],
  '08-08': [[1963, 'The Great Train Robbery took place in Buckinghamshire.', 'culture'],
            [1974, 'Richard Nixon announced his resignation.', 'politics']],
  '08-09': [[1945, 'An atomic bomb was dropped on Nagasaki.', 'disaster'],
            [1173, 'Construction began on the tower at Pisa.', 'culture']],
  '08-10': [[1846, 'The Smithsonian Institution was founded.', 'science'],
            [1675, 'The foundation stone of the Royal Observatory, Greenwich was laid.', 'science']],
  '08-11': [[1999, 'A total solar eclipse crossed Europe and Asia.', 'science'],
            [1965, 'The Watts uprising began in Los Angeles.', 'rights']],
  '08-12': [[1981, 'IBM introduced its first personal computer.', 'tech'],
            [1877, 'Asaph Hall discovered Deimos, a moon of Mars.', 'science']],
  '08-13': [[1961, 'Construction of the Berlin Wall began.', 'politics'],
            [1889, 'William Gray patented the coin-operated telephone.', 'tech']],
  '08-14': [[1945, 'Japan announced its surrender, ending the Second World War.', 'politics'],
            [1935, 'The US Social Security Act was signed.', 'rights']],
  '08-15': [[1947, 'India and Pakistan became independent.', 'rights'],
            [1969, 'The Woodstock festival opened in New York State.', 'culture']],
  '08-16': [[1960, 'Joseph Kittinger parachuted from the edge of space.', 'exploration'],
            [1977, 'Elvis Presley died at Graceland.', 'culture']],
  '08-17': [[1807, 'Robert Fulton\u2019s steamboat began its first commercial voyage.', 'tech'],
            [1978, 'The first successful transatlantic balloon crossing was completed.', 'exploration']],
  '08-18': [[1920, 'US women won the vote with the Nineteenth Amendment.', 'rights'],
            [1868, 'Helium was discovered during a solar eclipse in India.', 'science']],
  '08-19': [[1839, 'The daguerreotype photographic process was given to the world.', 'tech'],
            [1934, 'A plebiscite confirmed Hitler as head of state in Germany.', 'politics']],
  '08-20': [[1977, 'Voyager 2 was launched on its grand tour of the outer planets.', 'exploration'],
            [1975, 'Viking 1 was launched towards Mars.', 'exploration']],
  '08-21': [[1911, 'The Mona Lisa was stolen from the Louvre.', 'culture'],
            [1959, 'Hawaii became the 50th US state.', 'politics']],
  '08-22': [[1864, 'The first Geneva Convention was signed.', 'rights'],
            [1962, 'The Mona Lisa left France for the first time in centuries, bound for Washington.', 'culture']],
  '08-23': [[1305, 'William Wallace was executed in London.', 'politics'],
            [1991, 'The World Wide Web became available to the wider public.', 'tech']],
  '08-24': [[79, 'Vesuvius erupted, burying Pompeii and Herculaneum.', 'disaster'],
            [1995, 'Microsoft released Windows 95.', 'tech']],
  '08-25': [[1835, 'The New York Sun began the Great Moon Hoax.', 'culture'],
            [1989, 'Voyager 2 made its closest approach to Neptune.', 'exploration']],
  '08-26': [[1789, 'France adopted the Declaration of the Rights of Man.', 'rights'],
            [1883, 'Krakatoa erupted, heard thousands of miles away.', 'disaster']],
  '08-27': [[1859, 'The first successful oil well was drilled in Pennsylvania.', 'tech'],
            [1955, 'The first Guinness Book of Records was published.', 'culture']],
  '08-28': [[1963, 'Martin Luther King Jr. delivered \u201cI Have a Dream\u201d in Washington.', 'rights'],
            [1833, 'Britain\u2019s Slavery Abolition Act received royal assent.', 'rights']],
  '08-29': [[2005, 'Hurricane Katrina made landfall on the US Gulf Coast.', 'disaster'],
            [1949, 'The Soviet Union tested its first atomic bomb.', 'politics']],
  '08-30': [[1963, 'The Washington\u2013Moscow hotline went into operation.', 'politics'],
            [1871, 'Ernest Rutherford, who first split the atom, was born in New Zealand.', 'science']],
  '08-31': [[1888, 'The first of the Whitechapel murders was reported in London.', 'culture'],
            [1997, 'Diana, Princess of Wales died in Paris.', 'culture']],

  '09-01': [[1939, 'Germany invaded Poland, beginning the Second World War in Europe.', 'politics'],
            [1985, 'The wreck of the Titanic was located on the sea floor.', 'exploration']],
  '09-02': [[1666, 'The Great Fire of London began.', 'disaster'],
            [1945, 'Japan formally surrendered aboard the USS Missouri.', 'politics']],
  '09-03': [[1783, 'The Treaty of Paris ended the American War of Independence.', 'politics'],
            [1976, 'Viking 2 landed on Mars.', 'exploration']],
  '09-04': [[1998, 'Google was founded in California.', 'tech'],
            [1888, 'George Eastman registered the Kodak trademark.', 'tech']],
  '09-05': [[1977, 'Voyager 1 was launched.', 'exploration'],
            [1972, 'The Munich Olympics attack took place.', 'disaster']],
  '09-06': [[1522, 'Magellan\u2019s expedition completed the first circumnavigation of the globe.', 'exploration'],
            [1997, 'The funeral of Diana, Princess of Wales was watched worldwide.', 'culture']],
  '09-07': [[1940, 'The Blitz began with heavy bombing of London.', 'disaster'],
            [1979, 'ESPN began broadcasting.', 'sport']],
  '09-08': [[1966, 'Star Trek was first broadcast.', 'culture'],
            [1504, 'Michelangelo\u2019s David was unveiled in Florence.', 'culture']],
  '09-09': [[1947, 'Engineers recorded the first computer \u201cbug\u201d \u2014 an actual moth.', 'tech'],
            [1850, 'California became the 31st US state.', 'politics']],
  '09-10': [[2008, 'The Large Hadron Collider circulated its first beam.', 'science'],
            [1846, 'Elias Howe patented the lockstitch sewing machine.', 'tech']],
  '09-11': [[2001, 'Coordinated attacks struck New York and Washington.', 'disaster'],
            [1997, 'Scotland voted for its own parliament.', 'politics']],
  '09-12': [[1962, 'Kennedy gave his \u201cWe choose to go to the Moon\u201d speech at Rice University.', 'exploration'],
            [1940, 'The Lascaux cave paintings were discovered in France.', 'culture']],
  '09-13': [[1985, 'Super Mario Bros. was released in Japan.', 'culture'],
            [1848, 'Phineas Gage survived an iron rod through the brain, transforming neurology.', 'science']],
  '09-14': [[1959, 'Luna 2 became the first craft to reach the surface of the Moon.', 'exploration'],
            [1814, 'Francis Scott Key wrote the poem that became the US anthem.', 'culture']],
  '09-15': [[1835, 'The Beagle reached the Gal\u00e1pagos Islands with Darwin aboard.', 'science'],
            [1928, 'Alexander Fleming discovered penicillin.', 'science']],
  '09-16': [[1620, 'The Mayflower set sail from Plymouth.', 'exploration'],
            [1987, 'The Montreal Protocol on the ozone layer was signed.', 'science']],
  '09-17': [[1787, 'The US Constitution was signed in Philadelphia.', 'politics'],
            [1976, 'NASA unveiled the first Space Shuttle, Enterprise.', 'exploration']],
  '09-18': [[1793, 'The cornerstone of the US Capitol was laid.', 'politics'],
            [1851, 'The New York Times published its first issue.', 'culture']],
  '09-19': [[1991, 'The frozen body of \u00d6tzi the Iceman was found in the Alps.', 'science'],
            [1893, 'New Zealand became the first country to give women the vote.', 'rights']],
  '09-20': [[1519, 'Magellan set out from Spain on the first circumnavigation.', 'exploration'],
            [1946, 'The first Cannes Film Festival opened.', 'culture']],
  '09-21': [[1937, 'The Hobbit was published.', 'culture'],
            [1981, 'Belize became independent from the United Kingdom.', 'politics']],
  '09-22': [[1862, 'Lincoln issued the preliminary Emancipation Proclamation.', 'rights'],
            [1980, 'The Iran\u2013Iraq War began.', 'politics']],
  '09-23': [[1846, 'Neptune was discovered, predicted first by mathematics.', 'science'],
            [1889, 'Nintendo was founded in Kyoto as a playing-card company.', 'culture']],
  '09-24': [[1960, 'The first nuclear-powered aircraft carrier, USS Enterprise, was launched.', 'tech'],
            [1852, 'The first powered airship flew, near Paris.', 'tech']],
  '09-25': [[1957, 'Federal troops escorted the Little Rock Nine into school.', 'rights'],
            [1789, 'The US Bill of Rights was proposed to the states.', 'rights']],
  '09-26': [[1960, 'The first televised US presidential debate was broadcast.', 'politics'],
            [1983, 'Stanislav Petrov judged a nuclear alert to be a false alarm, and was right.', 'politics']],
  '09-27': [[1905, 'Einstein published the paper containing E=mc\u00b2.', 'science'],
            [1998, 'The Google search engine was formally launched.', 'tech']],
  '09-28': [[1928, 'Fleming returned from holiday to find mould killing his bacteria.', 'science'],
            [1066, 'William of Normandy landed in England.', 'politics']],
  '09-29': [[1954, 'CERN was founded in Geneva.', 'science'],
            [1988, 'Discovery returned the shuttle fleet to flight after Challenger.', 'exploration']],
  '09-30': [[1935, 'The Hoover Dam was dedicated.', 'tech'],
            [1955, 'James Dean died in a car crash in California.', 'culture']],
  '10-01': [[1949, 'The People\u2019s Republic of China was proclaimed in Beijing.', 'politics'],
            [1908, 'The Ford Model T went on sale.', 'tech']],
  '10-02': [[1869, 'Mohandas Gandhi was born in Porbandar.', 'rights'],
            [1950, 'The Peanuts comic strip first appeared.', 'culture']],
  '10-03': [[1990, 'East and West Germany were reunified.', 'politics'],
            [1955, 'The Mickey Mouse Club began broadcasting.', 'culture']],
  '10-04': [[1957, 'Sputnik 1 became the first artificial satellite.', 'exploration'],
            [1957, 'The Space Age began, and with it the space race.', 'exploration']],
  '10-05': [[1962, 'The Beatles released their first single, Love Me Do.', 'culture'],
            [1969, 'Monty Python\u2019s Flying Circus was first broadcast.', 'culture']],
  '10-06': [[1927, 'The Jazz Singer opened, ushering in sound cinema.', 'culture'],
            [1889, 'The Moulin Rouge opened in Paris.', 'culture']],
  '10-07': [[1959, 'Luna 3 sent back the first photographs of the Moon\u2019s far side.', 'exploration'],
            [1806, 'Carbon paper was patented in London.', 'tech']],
  '10-08': [[1871, 'The Great Chicago Fire began.', 'disaster'],
            [1967, 'Che Guevara was captured in Bolivia.', 'politics']],
  '10-09': [[1604, 'Kepler\u2019s Supernova was first observed.', 'science'],
            [1967, 'Che Guevara was executed.', 'politics']],
  '10-10': [[1911, 'The Xinhai Revolution began, ending imperial rule in China.', 'politics'],
            [1913, 'The Panama Canal\u2019s final barrier was blasted away.', 'tech']],
  '10-11': [[1968, 'Apollo 7 launched, the first crewed Apollo mission.', 'exploration'],
            [1975, 'Saturday Night Live was first broadcast.', 'culture']],
  '10-12': [[1492, 'Columbus\u2019s expedition made landfall in the Bahamas.', 'exploration'],
            [1810, 'The first Oktoberfest was held in Munich.', 'culture']],
  '10-13': [[1792, 'The cornerstone of the White House was laid.', 'politics'],
            [1884, 'Greenwich was adopted as the world\u2019s prime meridian.', 'science']],
  '10-14': [[1947, 'Chuck Yeager broke the sound barrier.', 'tech'],
            [1066, 'The Battle of Hastings was fought.', 'politics']],
  '10-15': [[1997, 'Cassini was launched towards Saturn.', 'exploration'],
            [1878, 'The Edison Electric Light Company was incorporated.', 'tech']],
  '10-16': [[1846, 'Ether anaesthesia was publicly demonstrated in Boston.', 'science'],
            [1978, 'John Paul II became the first Polish pope.', 'culture']],
  '10-17': [[1931, 'Al Capone was convicted of tax evasion.', 'politics'],
            [1933, 'Albert Einstein arrived in the United States as a refugee.', 'science']],
  '10-18': [[1867, 'The United States formally took possession of Alaska.', 'politics'],
            [1922, 'The BBC was founded.', 'culture']],
  '10-19': [[1987, 'Stock markets crashed worldwide on Black Monday.', 'politics'],
            [1781, 'British forces surrendered at Yorktown.', 'politics']],
  '10-20': [[1973, 'The Sydney Opera House was opened.', 'culture'],
            [1968, 'Jacqueline Kennedy married Aristotle Onassis.', 'culture']],
  '10-21': [[1879, 'Edison tested the carbon-filament lamp that burned for hours.', 'tech'],
            [1805, 'The Battle of Trafalgar was fought off the Spanish coast.', 'politics']],
  '10-22': [[1962, 'Kennedy announced the naval quarantine of Cuba.', 'politics'],
            [1797, 'Andr\u00e9-Jacques Garnerin made the first parachute descent.', 'exploration']],
  '10-23': [[1707, 'The first Parliament of Great Britain met.', 'politics'],
            [2001, 'Apple introduced the iPod.', 'tech']],
  '10-24': [[1945, 'The United Nations formally came into existence.', 'politics'],
            [1901, 'Annie Edson Taylor went over Niagara Falls in a barrel and survived.', 'culture']],
  '10-25': [[1881, 'Pablo Picasso was born in M\u00e1laga.', 'culture'],
            [1971, 'The People\u2019s Republic of China took China\u2019s UN seat.', 'politics']],
  '10-26': [[1825, 'The Erie Canal opened.', 'tech'],
            [1881, 'The gunfight at the O.K. Corral took place in Tombstone.', 'culture']],
  '10-27': [[1904, 'The New York City subway opened.', 'tech'],
            [1962, 'Vasili Arkhipov refused to approve a nuclear launch during the Cuban crisis.', 'politics']],
  '10-28': [[1886, 'The Statue of Liberty was dedicated.', 'culture'],
            [1962, 'Khrushchev agreed to remove Soviet missiles from Cuba.', 'politics']],
  '10-29': [[1969, 'The first message was sent over ARPANET, ancestor of the internet.', 'tech'],
            [1929, 'Wall Street crashed on Black Tuesday.', 'politics']],
  '10-30': [[1938, 'Orson Welles broadcast The War of the Worlds.', 'culture'],
            [1961, 'The Soviet Union tested the Tsar Bomba, the largest ever detonated.', 'politics']],
  '10-31': [[1517, 'Martin Luther is said to have published his Ninety-five Theses.', 'culture'],
            [1941, 'Mount Rushmore was completed.', 'culture']],

  '11-01': [[1512, 'Michelangelo\u2019s Sistine Chapel ceiling was shown to the public.', 'culture'],
            [1952, 'The first hydrogen bomb was detonated in the Pacific.', 'science']],
  '11-02': [[1936, 'The BBC began the world\u2019s first regular television service.', 'tech'],
            [2000, 'The first crew arrived to live aboard the International Space Station.', 'exploration']],
  '11-03': [[1957, 'Laika became the first animal to orbit the Earth.', 'exploration'],
            [1957, 'Sputnik 2 carried a living passenger into orbit.', 'exploration']],
  '11-04': [[1922, 'Howard Carter found the entrance to Tutankhamun\u2019s tomb.', 'culture'],
            [2008, 'Barack Obama was elected US president.', 'rights']],
  '11-05': [[1605, 'The Gunpowder Plot was uncovered in London.', 'politics'],
            [1895, 'The first US patent for an automobile was granted.', 'tech']],
  '11-06': [[1860, 'Abraham Lincoln was elected president.', 'politics'],
            [1869, 'The first intercollegiate American football game was played.', 'sport']],
  '11-07': [[1867, 'Marie Curie was born in Warsaw.', 'science'],
            [1917, 'The October Revolution began in Petrograd.', 'politics']],
  '11-08': [[1895, 'Wilhelm R\u00f6ntgen discovered X-rays.', 'science'],
            [1889, 'Montana became the 41st US state.', 'politics']],
  '11-09': [[1989, 'The Berlin Wall was opened.', 'rights'],
            [1967, 'The first Saturn V rocket was launched, uncrewed.', 'exploration']],
  '11-10': [[1969, 'Sesame Street was first broadcast.', 'culture'],
            [1871, 'Stanley is said to have greeted Livingstone in central Africa.', 'exploration']],
  '11-11': [[1918, 'The armistice ended fighting in the First World War.', 'politics'],
            [1620, 'The Mayflower Compact was signed.', 'politics']],
  '11-12': [[1990, 'Tim Berners-Lee published his formal proposal for the World Wide Web.', 'tech'],
            [1927, 'Stalin consolidated power by expelling Trotsky from the party.', 'politics']],
  '11-13': [[1940, 'Disney\u2019s Fantasia premiered.', 'culture'],
            [1956, 'The US Supreme Court ruled bus segregation unconstitutional.', 'rights']],
  '11-14': [[1969, 'Apollo 12 launched and was struck by lightning seconds later.', 'exploration'],
            [1889, 'Nellie Bly set out to travel around the world in under 80 days.', 'exploration']],
  '11-15': [[1969, 'Half a million people marched in Washington against the Vietnam War.', 'rights'],
            [1971, 'Intel released the 4004, the first commercial microprocessor.', 'tech']],
  '11-16': [[1945, 'UNESCO was founded.', 'culture'],
            [1974, 'The Arecibo message was beamed towards a distant star cluster.', 'science']],
  '11-17': [[1970, 'Douglas Engelbart received the patent for the computer mouse.', 'tech'],
            [1869, 'The Suez Canal opened.', 'tech']],
  '11-18': [[1928, 'Steamboat Willie premiered, introducing sound-synchronised animation.', 'culture'],
            [1883, 'North American railways adopted standard time zones.', 'tech']],
  '11-19': [[1863, 'Lincoln delivered the Gettysburg Address.', 'politics'],
            [1969, 'Apollo 12 astronauts made the second Moon landing.', 'exploration']],
  '11-20': [[1947, 'Princess Elizabeth married Philip Mountbatten.', 'culture'],
            [1945, 'The Nuremberg trials began.', 'rights']],
  '11-21': [[1783, 'The first free flight with human passengers rose over Paris in a balloon.', 'exploration'],
            [1877, 'Edison announced his invention of the phonograph.', 'tech']],
  '11-22': [[1963, 'John F. Kennedy was assassinated in Dallas.', 'politics'],
            [1990, 'Margaret Thatcher announced her resignation.', 'politics']],
  '11-23': [[1963, 'Doctor Who was first broadcast.', 'culture'],
            [1936, 'The first issue of Life magazine appeared.', 'culture']],
  '11-24': [[1859, 'Darwin published On the Origin of Species.', 'science'],
            [1974, 'The fossil skeleton \u201cLucy\u201d was discovered in Ethiopia.', 'science']],
  '11-25': [[1867, 'Alfred Nobel patented dynamite.', 'tech'],
            [1915, 'Einstein presented the field equations of general relativity.', 'science']],
  '11-26': [[1922, 'Carter and Carnarvon first entered Tutankhamun\u2019s tomb.', 'culture'],
            [1942, 'Casablanca premiered in New York.', 'culture']],
  '11-27': [[1895, 'Alfred Nobel signed the will that created the Nobel Prizes.', 'science'],
            [1701, 'Anders Celsius, who devised the temperature scale, was born.', 'science']],
  '11-28': [[1520, 'Magellan\u2019s ships entered the Pacific Ocean.', 'exploration'],
            [1943, 'The Tehran Conference of Allied leaders began.', 'politics']],
  '11-29': [[1929, 'Richard Byrd made the first flight over the South Pole.', 'exploration'],
            [1947, 'The UN voted to partition Palestine.', 'politics']],
  '11-30': [[1954, 'A meteorite struck a woman in Alabama, the first confirmed such case.', 'science'],
            [1874, 'Winston Churchill was born at Blenheim Palace.', 'politics']],

  '12-01': [[1955, 'Rosa Parks refused to give up her bus seat in Montgomery.', 'rights'],
            [1990, 'Workers met beneath the Channel, joining Britain and France.', 'tech']],
  '12-02': [[1942, 'The first controlled nuclear chain reaction was achieved in Chicago.', 'science'],
            [1982, 'The first permanent artificial heart was implanted.', 'science']],
  '12-03': [[1967, 'Christiaan Barnard performed the first human heart transplant.', 'science'],
            [1984, 'The Bhopal gas disaster occurred in India.', 'disaster']],
  '12-04': [[1791, 'The Observer, the world\u2019s oldest Sunday newspaper, was first published.', 'culture'],
            [1996, 'Mars Pathfinder was launched.', 'exploration']],
  '12-05': [[1933, 'Prohibition ended in the United States.', 'politics'],
            [1791, 'Mozart died in Vienna, aged 35.', 'culture']],
  '12-06': [[1877, 'Edison made the first recording of a human voice.', 'tech'],
            [1917, 'A munitions explosion devastated Halifax, Nova Scotia.', 'disaster']],
  '12-07': [[1941, 'Pearl Harbor was attacked.', 'politics'],
            [1972, 'Apollo 17 launched, the last crewed mission to the Moon.', 'exploration']],
  '12-08': [[1980, 'John Lennon was shot in New York.', 'culture'],
            [1987, 'The US and USSR signed the treaty eliminating intermediate-range missiles.', 'politics']],
  '12-09': [[1968, 'Douglas Engelbart gave the demonstration later called \u201cthe mother of all demos\u201d.', 'tech'],
            [1979, 'Smallpox was certified as eradicated worldwide.', 'science']],
  '12-10': [[1948, 'The UN adopted the Universal Declaration of Human Rights.', 'rights'],
            [1901, 'The first Nobel Prizes were awarded.', 'science']],
  '12-11': [[1997, 'The Kyoto Protocol was adopted.', 'science'],
            [1936, 'Edward VIII abdicated the British throne.', 'politics']],
  '12-12': [[1901, 'Marconi received the first transatlantic radio signal.', 'tech'],
            [1913, 'The Mona Lisa was recovered in Florence.', 'culture']],
  '12-13': [[1577, 'Francis Drake set out to circumnavigate the globe.', 'exploration'],
            [1972, 'The last humans to date left the surface of the Moon.', 'exploration']],
  '12-14': [[1911, 'Roald Amundsen\u2019s party reached the South Pole.', 'exploration'],
            [1900, 'Max Planck presented the idea that began quantum theory.', 'science']],
  '12-15': [[1791, 'The US Bill of Rights was ratified.', 'rights'],
            [1970, 'Venera 7 made the first soft landing on another planet.', 'exploration']],
  '12-16': [[1773, 'The Boston Tea Party took place.', 'politics'],
            [1770, 'Ludwig van Beethoven was baptised in Bonn.', 'culture']],
  '12-17': [[1903, 'The Wright brothers made the first powered flight at Kitty Hawk.', 'tech'],
            [1989, 'The Simpsons began as a series.', 'culture']],
  '12-18': [[1865, 'The Thirteenth Amendment abolished slavery in the United States.', 'rights'],
            [1958, 'The first communications satellite broadcast a voice from orbit.', 'tech']],
  '12-19': [[1843, 'Dickens published A Christmas Carol.', 'culture'],
            [1972, 'Apollo 17 splashed down, ending the Apollo Moon programme.', 'exploration']],
  '12-20': [[1860, 'South Carolina became the first state to secede from the Union.', 'politics'],
            [1957, 'Elvis Presley received his draft notice.', 'culture']],
  '12-21': [[1968, 'Apollo 8 launched, carrying the first humans towards the Moon.', 'exploration'],
            [1937, 'Snow White and the Seven Dwarfs premiered.', 'culture']],
  '12-22': [[1808, 'Beethoven\u2019s Fifth and Sixth symphonies premiered in one long concert.', 'culture'],
            [1990, 'Lech Wa\u0142\u0119sa was sworn in as president of Poland.', 'politics']],
  '12-23': [[1947, 'The transistor was demonstrated at Bell Labs.', 'tech'],
            [1888, 'Vincent van Gogh cut off part of his ear in Arles.', 'culture']],
  '12-24': [[1968, 'Apollo 8 orbited the Moon and photographed Earthrise.', 'exploration'],
            [1818, 'Silent Night was performed for the first time, in Austria.', 'culture']],
  '12-25': [[1990, 'The first successful web page was served at CERN.', 'tech'],
            [1642, 'Isaac Newton was born, by the calendar then in use in England.', 'science']],
  '12-26': [[2004, 'An Indian Ocean earthquake caused a devastating tsunami.', 'disaster'],
            [1898, 'The Curies announced the discovery of radium.', 'science']],
  '12-27': [[1831, 'Charles Darwin set sail aboard HMS Beagle.', 'science'],
            [1945, 'The World Bank and IMF were established.', 'politics']],
  '12-28': [[1895, 'The Lumi\u00e8re brothers held the first paying public film screening.', 'culture'],
            [1612, 'Galileo observed Neptune, mistaking it for a star.', 'science']],
  '12-29': [[1170, 'Thomas Becket was murdered in Canterbury Cathedral.', 'politics'],
            [1911, 'Sun Yat-sen was elected provisional president of the Republic of China.', 'politics']],
  '12-30': [[1922, 'The Soviet Union was formally established.', 'politics'],
            [2006, 'Saddam Hussein was executed in Baghdad.', 'politics']],
  '12-31': [[1999, 'The Panama Canal was handed over to Panama.', 'politics'],
            [1907, 'The first New Year\u2019s Eve ball dropped in Times Square.', 'culture']],
};

/* ------------------------------------------------------------------ */
/* lookup                                                              */
/* ------------------------------------------------------------------ */
export const dayKeyOf = (d = new Date()) =>
  `${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;

/** Everything bundled for a given date, newest first. */
export function forDate(date = new Date()) {
  const rows = HISTORY[dayKeyOf(date)] || [];
  return rows
    .map(([year, text, tag]) => ({ year, text, tag, source: 'bundled' }))
    .sort((a, b) => b.year - a.year);
}

/**
 * One event, chosen deterministically for the date, so the widget shows the
 * same thing all day rather than shuffling every time you glance at it.
 */
export function pickForDate(date = new Date(), seed = 0) {
  const all = forDate(date);
  if (!all.length) return null;
  const n = date.getFullYear() + date.getMonth() * 31 + date.getDate() + seed;
  return all[n % all.length];
}

/** How many years ago, phrased plainly. */
export function yearsAgo(year, now = new Date()) {
  const n = now.getFullYear() - year;
  return n <= 0 ? 0 : n;
}

/** Coverage check — used by the tests to prove no day is left blank. */
export function coverage() {
  const days = Object.keys(HISTORY);
  const events = days.reduce((a, k) => a + HISTORY[k].length, 0);
  return { days: days.length, events };
}

/**
 * Optional enrichment from Wikipedia's public feed. No key, no account, and it
 * sends nothing about the person — only the month and day. Fails silently, so
 * the bundled set is always what you fall back to.
 */
export async function enrich(date = new Date(), { timeout = 6000, fetchImpl } = {}) {
  const f = fetchImpl || (typeof fetch !== 'undefined' ? fetch : null);
  if (!f) return [];
  const mm = String(date.getMonth() + 1).padStart(2, '0');
  const dd = String(date.getDate()).padStart(2, '0');
  const url = `https://api.wikimedia.org/feed/v1/wikipedia/en/onthisday/selected/${mm}/${dd}`;
  const ctrl = typeof AbortController !== 'undefined' ? new AbortController() : null;
  const timer = ctrl ? setTimeout(() => ctrl.abort(), timeout) : null;
  try {
    const res = await f(url, { signal: ctrl?.signal, headers: { accept: 'application/json' } });
    if (!res.ok) return [];
    const data = await res.json();
    return (data.selected || [])
      .filter((e) => e && e.year && e.text)
      .map((e) => ({ year: e.year, text: String(e.text), tag: 'culture', source: 'wikipedia' }));
  } catch {
    return [];
  } finally {
    if (timer) clearTimeout(timer);
  }
}

/** Bundled first, then anything new from the network, de-duplicated by year. */
export function merge(bundled, extra) {
  const seen = new Set(bundled.map((e) => `${e.year}`));
  const add = extra.filter((e) => !seen.has(`${e.year}`));
  return [...bundled, ...add].sort((a, b) => b.year - a.year);
}

/**
 * A tiny snapshot for the native home-screen and watch widgets.
 *
 * Web code cannot draw a widget — only native code can. So the shell asks for
 * this, writes it into the shared container, and the widget reads it. Small on
 * purpose: widgets are refreshed by the OS on its own schedule and should never
 * carry a whole archive.
 */
export function widgetSnapshot({ date = new Date(), diary = {}, locale = 'en-GB' } = {}) {
  const event = pickForDate(date);
  return {
    v: 1,
    generated: date.toISOString(),
    locale,
    history: event
      ? { year: event.year, text: event.text, tag: event.tag, yearsAgo: yearsAgo(event.year, date) }
      : null,
    diary: {
      title: diary.title || null,
      placard: diary.placard || null,
      kept: diary.kept ?? 0,
      streak: diary.streak ?? 0,
      onThisDay: diary.onThisDay || null,
    },
  };
}
