import test from 'node:test';
import assert from 'node:assert/strict';
import { webcrypto } from 'node:crypto';
import * as L from '../licence.js';
import * as B from '../business.js';

if (!globalThis.crypto?.subtle) globalThis.crypto = webcrypto;

/* Generate a throwaway pair so the tests never depend on a shipped key. */
const pair = await webcrypto.subtle.generateKey(
  { name: 'ECDSA', namedCurve: 'P-256' }, true, ['sign', 'verify']);
const PUB = await webcrypto.subtle.exportKey('jwk', pair.publicKey);

const b64url = (buf) => Buffer.from(buf).toString('base64')
  .replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');

async function issue(claims) {
  const body = b64url(new TextEncoder().encode(JSON.stringify(claims)));
  const sig = await webcrypto.subtle.sign({ name: 'ECDSA', hash: 'SHA-256' },
    pair.privateKey, new TextEncoder().encode(body));
  return `CURIO-1.${body}.${b64url(sig)}`;
}

const BASE = { v: 1, tier: 'business', name: 'Adom Ltd', email: 'ops@adom.example',
               seats: 3, id: 'CUR-TEST', issued: '2026-07-24', expires: null };

/* ================= SELLING WITHOUT A SERVER ================= */
test('a properly signed licence is accepted', async () => {
  const r = await L.verify(await issue(BASE), { publicKey: PUB });
  assert.equal(r.valid, true);
  assert.equal(r.claims.name, 'Adom Ltd');
  assert.equal(r.claims.seats, 3);
});

test('the claims are readable before verifying, so a buyer sees what they bought', async () => {
  const claims = L.peek(await issue(BASE));
  assert.equal(claims.name, 'Adom Ltd');
  assert.equal(claims.tier, 'business');
  assert.equal(L.peek('rubbish'), null);
});

test('a tampered licence is refused', async () => {
  const lic = await issue(BASE);
  const [prefix, body, sig] = lic.split('.');
  const claims = JSON.parse(Buffer.from(body, 'base64url').toString());
  claims.seats = 999;
  const forged = `${prefix}.${b64url(Buffer.from(JSON.stringify(claims)))}.${sig}`;
  const r = await L.verify(forged, { publicKey: PUB });
  assert.equal(r.valid, false);
  assert.equal(r.reason, 'BAD_SIGNATURE');
});

test('a licence signed by somebody else is refused', async () => {
  const other = await webcrypto.subtle.generateKey(
    { name: 'ECDSA', namedCurve: 'P-256' }, true, ['sign', 'verify']);
  const body = b64url(new TextEncoder().encode(JSON.stringify(BASE)));
  const sig = await webcrypto.subtle.sign({ name: 'ECDSA', hash: 'SHA-256' },
    other.privateKey, new TextEncoder().encode(body));
  const r = await L.verify(`CURIO-1.${body}.${b64url(sig)}`, { publicKey: PUB });
  assert.equal(r.valid, false);
  assert.equal(r.reason, 'BAD_SIGNATURE');
});

test('rubbish is refused with a reason rather than a crash', async () => {
  for (const [input, reason] of [['', 'NOT_A_LICENCE'], ['hello', 'NOT_A_LICENCE'],
    ['CURIO-1.nodot', 'MALFORMED'], ['CURIO-1.!!!.???', 'MALFORMED']]) {
    const r = await L.verify(input, { publicKey: PUB });
    assert.equal(r.valid, false);
    assert.equal(r.reason, reason, `input ${JSON.stringify(input)}`);
  }
});

test('an expired trial stops working, and a perpetual licence does not', async () => {
  const trial = await issue({ ...BASE, expires: '2026-01-01' });
  const r = await L.verify(trial, { publicKey: PUB, now: new Date('2026-07-24') });
  assert.equal(r.valid, false);
  assert.equal(r.reason, 'EXPIRED');

  const stillGood = await L.verify(trial, { publicKey: PUB, now: new Date('2025-12-01') });
  assert.equal(stillGood.valid, true);

  const perpetual = await L.verify(await issue(BASE), { publicKey: PUB, now: new Date('2099-01-01') });
  assert.equal(perpetual.valid, true, 'a perpetual licence never lapses');
});

test('the shipped file has no key in it, so nobody inherits mine', async () => {
  assert.match(L.PUBLIC_KEY_JWK.x, /^REPLACE-WITH/, 'a real key must be generated by the seller');
  const r = await L.verify(await issue(BASE));
  assert.equal(r.reason, 'NO_KEY_CONFIGURED');
});

test('a support code identifies a licence without exposing it', async () => {
  const lic = await issue(BASE);
  const code = await L.shortCode(lic);
  assert.match(code, /^[0-9A-F]{4}-[0-9A-F]{4}$/);
  assert.equal(code, await L.shortCode(lic), 'stable');
  assert.notEqual(code, await L.shortCode(await issue({ ...BASE, id: 'OTHER' })));
});

/* ================= WHAT IS FREE, AND WHAT IS NOT ================= */
test('the personal diary is never gated', () => {
  for (const f of ['capture', 'search', 'themes', 'recovery', 'anythingElse']) {
    assert.equal(L.has(f, L.TIERS.FREE), true, `${f} must stay free`);
  }
});

test('the work features are what business pays for', () => {
  for (const f of ['workspaces', 'templates', 'integrity', 'reports', 'bulkExport']) {
    assert.equal(L.has(f, L.TIERS.FREE), false, `${f} should be a business feature`);
    assert.equal(L.has(f, L.TIERS.BUSINESS), true);
  }
  assert.equal(L.isBusiness(L.TIERS.BUSINESS), true);
  assert.equal(L.isBusiness(L.TIERS.FREE), false);
});

/* ================= TEMPLATES ================= */
test('the templates cover real field work', () => {
  const ids = B.TEMPLATES.map((t) => t.id);
  for (const id of ['site-inspection', 'client-visit', 'incident', 'delivery', 'fieldwork']) {
    assert.ok(ids.includes(id), `${id} is missing`);
  }
  for (const t of B.TEMPLATES) {
    assert.ok(t.fields.length >= 4, `${t.id} is too thin`);
    assert.ok(t.fields.some((f) => f.required), `${t.id} has nothing required`);
    for (const f of t.fields) {
      assert.ok(f.key && f.label && f.kind, `${t.id}: a field is incomplete`);
      assert.ok(Object.values(B.FIELD).includes(f.kind), `${t.id}: unknown kind ${f.kind}`);
    }
  }
});

test('required fields are enforced', () => {
  const t = B.templateById('incident');
  assert.deepEqual(B.missingRequired(t, {}).sort(), ['severity', 'what', 'where']);
  assert.deepEqual(B.missingRequired(t, { where: 'Yard', what: 'A fall', severity: 'High' }), []);
  assert.deepEqual(B.missingRequired(t, { where: '   ', what: 'x', severity: 'y' }), ['where'],
    'whitespace is not an answer');
});

test('a completed record summarises itself', () => {
  const t = B.templateById('site-inspection');
  const s = B.summarise(t, { site: 'Plot 14', findings: 'Water ingress', severity: 'High' });
  assert.match(s, /Plot 14/);
  assert.match(s, /High/);
  const lines = B.asLines(t, { site: 'Plot 14', findings: 'Water ingress', ref: '' });
  assert.equal(lines.length, 2, 'empty fields are left out');
});

/* ================= INTEGRITY ================= */
test('a sealed chain verifies while nothing has changed', async () => {
  const recs = [
    { id: 'r1', at: '2026-07-20T09:00:00Z', kind: 'note', title: 'A', placard: 'one' },
    { id: 'r2', at: '2026-07-21T09:00:00Z', kind: 'note', title: 'B', placard: 'two' },
    { id: 'r3', at: '2026-07-22T09:00:00Z', kind: 'note', title: 'C', placard: 'three' },
  ];
  const sealed = await B.sealChain(recs);
  assert.equal(sealed.count, 3);
  assert.match(sealed.head, /^[0-9a-f]{64}$/);

  const check = await B.verifyChain(sealed.moments);
  assert.equal(check.ok, true);
  assert.equal(check.checked, 3);
  assert.equal(check.head, sealed.head);
});

test('altering a record afterwards is detected, and named', async () => {
  const recs = [
    { id: 'r1', at: '2026-07-20T09:00:00Z', kind: 'note', title: 'A', placard: 'one' },
    { id: 'r2', at: '2026-07-21T09:00:00Z', kind: 'note', title: 'B', placard: 'two' },
    { id: 'r3', at: '2026-07-22T09:00:00Z', kind: 'note', title: 'C', placard: 'three' },
  ];
  const sealed = await B.sealChain(recs);
  const tampered = sealed.moments.map((m) => m.id === 'r2' ? { ...m, placard: 'changed' } : m);
  const check = await B.verifyChain(tampered);
  assert.equal(check.ok, false);
  assert.equal(check.reason, 'ALTERED');
  assert.equal(check.failedAt, 'r2');
  assert.equal(check.title, 'B', 'it says which record, not just that something is wrong');
});

test('removing a record breaks the chain', async () => {
  const sealed = await B.sealChain([
    { id: 'r1', at: '2026-07-20T09:00:00Z', title: 'A', placard: 'one' },
    { id: 'r2', at: '2026-07-21T09:00:00Z', title: 'B', placard: 'two' },
    { id: 'r3', at: '2026-07-22T09:00:00Z', title: 'C', placard: 'three' },
  ]);
  const check = await B.verifyChain(sealed.moments.filter((m) => m.id !== 'r2'));
  assert.equal(check.ok, false);
  assert.equal(check.reason, 'BROKEN_LINK');
});

test('the seal covers the structured record, not just the prose', async () => {
  const base = { id: 'r1', at: '2026-07-20T09:00:00Z', title: 'A', placard: 'one',
                 record: { template: 'incident', values: { severity: 'Low' } } };
  const sealed = await B.sealChain([base]);
  const changed = [{ ...sealed.moments[0],
    record: { template: 'incident', values: { severity: 'Critical' } } }];
  const check = await B.verifyChain(changed);
  assert.equal(check.ok, false, 'changing a severity after the fact must be visible');
});

test('a photograph swapped for another is detected', async () => {
  const sealed = await B.sealChain([
    { id: 'r1', at: '2026-07-20T09:00:00Z', title: 'A', placard: 'one', photo: 'data:image/jpeg;base64,AAAA' },
  ]);
  const swapped = [{ ...sealed.moments[0], photo: 'data:image/jpeg;base64,AAAAAAAA' }];
  assert.equal((await B.verifyChain(swapped)).ok, false);
});

test('an empty chain is not a failure', async () => {
  const check = await B.verifyChain([]);
  assert.equal(check.ok, true);
  assert.equal(check.checked, 0);
});

test('a certificate carries a code a client can check against later', async () => {
  const sealed = await B.sealChain([{ id: 'r1', at: '2026-07-20T09:00:00Z', title: 'A', placard: 'x' }]);
  const cert = B.certificate(sealed, { name: 'Adom Ltd' });
  assert.equal(cert.records, 1);
  assert.equal(cert.head, sealed.head);
  assert.match(cert.short, /^[0-9A-F]{4}(-[0-9A-F]{4}){3}$/);
  assert.equal(cert.by, 'Adom Ltd');
});

/* ================= WORKSPACES ================= */
test('work and personal are kept apart', () => {
  const ms = [
    { id: 1, kept: true },
    { id: 2, workspace: 'work', kept: true },
    { id: 3, workspace: 'work', kept: true },
  ];
  assert.equal(B.workspaceOf(ms[0]), 'personal', 'anything unmarked is personal');
  assert.equal(B.inWorkspace(ms, 'work').length, 2);
  assert.equal(B.inWorkspace(ms, 'personal').length, 1);
  assert.deepEqual(B.workspaces(ms).sort(), ['personal', 'work']);
  assert.equal(B.workspaceCounts(ms).get('work'), 2);
});

test('a report gathers only the right workspace and range', () => {
  const ms = [
    { id: 1, workspace: 'work', kept: true, at: '2026-07-01T09:00:00Z',
      record: { template: 'incident', values: { severity: 'High' } } },
    { id: 2, workspace: 'work', kept: true, at: '2026-07-15T09:00:00Z', photo: 'x',
      record: { template: 'incident', values: { severity: 'Low' } } },
    { id: 3, workspace: 'work', kept: true, at: '2026-09-01T09:00:00Z' },
    { id: 4, kept: true, at: '2026-07-10T09:00:00Z' },
  ];
  const r = B.reportData(ms, { from: new Date('2026-07-01'), to: new Date('2026-07-31'), workspace: 'work' });
  assert.equal(r.count, 2, 'the personal entry and the out-of-range one are excluded');
  assert.equal(r.withPhotos, 1);
  assert.equal(r.severities.High, 1);
  assert.equal(r.byTemplate.get('incident').length, 2);
});
